# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDRjMjRjYTkzM2Q1MjJiYzI3MDBjM2QyYjkxMDdjNzM0OGZmNThmMGE3ZDYzNzZlZWFhMTQ3NjhkMTgyZWZmNTVlNTU0OTA1ODA0ZmVlN2VkZGYxMjBlYzBjMDEzODczMWJiMThhMDc2NGZlOWQ3ZTUxNGVlNmMxNGVmOTU4MDY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
