# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjA1NjI4YmRiNWM4NmJiYTExZjdhNTI4MDU1MjEzOTIyNGYzMGE0MDhkZDA4NDJhZGIwMmJiOWM1YzZmMDhjYWM1MDFlNWRkNjNhYTkxYjA1NGJlOTAyOTI3ZTA1Mzk5YzBiZTk4YWYyZWNmNjZjNDhmNmVlYmVjYmJkOWVlZTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
